############## PROJECT CONFIGURATION ##############

#Project Name.
project_name: "Perses Test"

#Author: Name of the operator. Used as a prefix to avoid name collision on.
author: "percom21"

######### EC2 Configuration #########

#Instance AWS type: Only compatible with machines that support kvm virtualization -> https://help.ubuntu.com/community/KVM/Installation.
instance_type: "i3en.metal"
#AWS Region.
region: "eu-west-1"

#AMI.
ami_id: "ami-035966e8adab4aaad"


######### Environment Configuration #########
  #### Set of devices ####

  # Id: Name of set of devices
  # Type: mobile
  # Devices: numbers of Android devices to deploy
  # #Android version: You can select 6 to 11.
  # CPU:  maximum amount of available CPU resources each device can use
    #(We recommend a minimum of 1.5)
  # RAM:  maximum amount of memory each device can use
    #(We recommend a minimum of 3g '3GB').

devices:
  - id: "Basic Devices"
    type: "mobile"
    devices: 50
    android_version: 9
    hardware:
      cpu: "2"
      ram: "3g"
  - id: "Medium Devices"
    type: "mobile"
    devices: 50
    android_version: 9
    hardware:
      cpu: "2.5"
      ram: "3g"
  - id: "Medium Devices"
    type: "mobile"
    devices: 41
    android_version: 10
    hardware:
      cpu: "4"
      ram: "4g"


#Application Id of Android App (can find it in the 'build.graddle' file of the application).
application_id: "com.spilab.percom21"

#Time to wait for the deployment of Android devices (1m '1 minute', 1h '1 hour')
#For example, for deploy 50 devices, wait 20m '20 minutes'
time_wait: "45m"

######### Tests Definition #########

tests:
  - id: "GUI Performance"
    type: "espresso"
  - id: "Observed Performance1"
    type: "apipecker"
    config:
      concurrentUsers: 3
      iterations: 5
      delay: 500
      url: "http://108.129.48.139/risk?device=Device1"
    expect:
      mean:
        under: 2000
  - id: "Observed Performance2"
    type: "apipecker"
    config:
      concurrentUsers: 6
      iterations: 8
      delay: 500
      url: "http://108.129.48.139/risk?device=Device2"
    expect:
      mean:
        under: 2000
